/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.revature;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        Driver classUnderTest = new Driver();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
